#! /usr/bin/env node

//In this program I have focused on three things
// 1) Made system to generate a random number.
// 2) Ask User to guess the number generated by the system.
// 3) Gave the user his asnwer that either He/She has guessed the right number or not.

// I want to add auto shuffle of console logs so that the user has options like MCQs in which I arange the numbers randomly  but Due to less knowledge of programing I didn't make it more attractive/user friendly but hope that i cant make these kind of changes in future.

import inquirer from "inquirer"

const randomNumber = Math.floor(Math.random()* 6 + 1)
const answer = await inquirer.prompt([{

    name: "userGuessedNumber",
    type: "number",
    message: "Please guess the a number generated by the system "

}]);
if (answer.userGuessedNumber === randomNumber) {
    console.log("Congratulation! You guessed right number")
} else {
    console.log("You guessed wrong number, Please try again")
}

